name = "hyde"
description = "A classic blog theme"
license = "MIT"
homepage = "https://github.com/choyer/hyde"
min_version = "0.11.0"
demo = "https://carl.hoyer.ca"

[extra]
hyde_sticky = true
hyde_reverse = false
hyde_theme = ""
hyde_links = [
]

[author]
name = "Carl Hoyer / Vincent Prouillet"
homepage = "https://carl.hoyer.ca"

[original]
author =  "mdo"
homepage = "http://markdotto.com/"
repo = "https://www.github.com/mdo/hyde"
